a=int(input("enter first number"))
b=int(input("enter second  number"))
c=int(input("enter third number"))
d=int(input("enter fourth number"))
e=int(input("enter fiveth number"))
print("Average",a+b+c+d+e/5)